#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 检查修改的文件列表中是否包含了 package.json 文件
if git diff --name-only --cached | grep -q '^package\.json$'; then
  # 如果包含，则执行 pnpm install 命令来更新 pnpm-lockfile 文件
  pnpm install
  git add pnpm-lock.yaml
fi

# 对 ts 和 eslint 进行检查
npm run tslint && npm run lint
